### ISSUE TITLE
QuickImport string splitting adjustment.

### ISSUE THREAD

**Issue by SinsOfSeven** [Seris0/Gustav0#1]
`split("-")` -> `rsplit("-",1)` in all cases in the QuickImport plugin, since we use it exlusively to chop off the hash part.
```py
>>> x = 'Yanagi-CutSceneBodyA-vb0=706abbf8.txt'
>>> print(x.split('-'))
['Yanagi', 'CutSceneBodyA', 'vb0=706abbf8.txt']
>>> print(x.rsplit('-',1))
['Yanagi-CutSceneBodyA', 'vb0=706abbf8.txt']
```

You may also want to adjust `vg.name.split(".")[0]` -> `vg.name.rsplit(".",1)[0]`

**Comment by Seris0** [comment]
Fixed in the commit 7f9e43e123991b3460a00d29e157d90023f49cf8
